<a href="https://colab.research.google.com/github/diego2003-her14/practca-analisis-datos-pandas/blob/main/Practica_de_Manipulaci%C3%B3n_de_datos_con_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importar el CSV

In [ ]:
import pandas as pd

url = 'https://gist.githubusercontent.com/ahcamachod/807a2c1cf6c19108b2b701ea1791ab45/raw/fb84f8b2d8917a89de26679eccdbc8f9c1d2e933/alumnos.csv'

pd.read_csv(url)

      Nombre  Edad  Nota   Aprobado
0    Alberto    20   7.5       True
1        Ana    18   NaN      False
2     Camila    27   2.5      False
3      David    18   5.0      False
4      Brian    21  10.0       True
5      Bruna    23   NaN      False
6    Daniela    21   7.0       True
7     Carlos    19   6.0      False
8     Alicia    35   5.6      False
9     Victor    28   NaN      False
10    Danilo    21   NaN      False
11   Ignacio    24   4.5      False
12  Stephany    26  10.0       True
13    Miriam    25   9.0       True
14     Pablo    37   NaN      False
15    Milena    29   7.0       True
16     Lucas    33   NaN      False
17     Nadia    34   8.0  Verdadero

## Visualizar la Tabla

In [ ]:
datos = pd.read_csv(url)
datos

      Nombre  Edad  Nota   Aprobado
0    Alberto    20   7.5       True
1        Ana    18   NaN      False
2     Camila    27   2.5      False
3      David    18   5.0      False
4      Brian    21  10.0       True
5      Bruna    23   NaN      False
6    Daniela    21   7.0       True
7     Carlos    19   6.0      False
8     Alicia    35   5.6      False
9     Victor    28   NaN      False
10    Danilo    21   NaN      False
11   Ignacio    24   4.5      False
12  Stephany    26  10.0       True
13    Miriam    25   9.0       True
14     Pablo    37   NaN      False
15    Milena    29   7.0       True
16     Lucas    33   NaN      False
17     Nadia    34   8.0  Verdadero

## Visualiza las primeras 7 filas del DataFrame

In [ ]:
datos.head(7)

    Nombre  Edad  Nota Aprobado
0  Alberto    20   7.5     True
1      Ana    18   NaN    False
2   Camila    27   2.5    False
3    David    18   5.0    False
4    Brian    21  10.0     True
5    Bruna    23   NaN    False
6  Daniela    21   7.0     True

## Visualizar las ultimas 5 filas del DataFrame

In [ ]:
datos.tail(5)

    Nombre  Edad  Nota   Aprobado
13  Miriam    25   9.0       True
14   Pablo    37   NaN      False
15  Milena    29   7.0       True
16   Lucas    33   NaN      False
17   Nadia    34   8.0  Verdadero

## Verificar la cantidad de filas y de columnas del DataFrame

In [ ]:
datos.shape

(18, 4)

## Explora las columnas del DataFrame y analiza los tipos de datos presentes en cada columna.

In [ ]:
datos.columns

Index(['Nombre', 'Edad', 'Nota', 'Aprobado'], dtype='object')

In [ ]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Nombre    18 non-null     object
 1   Edad      18 non-null     int64
 2   Nota      12 non-null     float64
 3   Aprobado  18 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 708.0+ bytes

In [ ]:
datos['Aprobado']

0          True
1         False
2         False
3         False
4          True
5         False
6          True
7         False
8         False
9         False
10        False
11        False
12         True
13         True
14        False
15         True
16        False
17    Verdadero
Name: Aprobado, dtype: object

In [ ]:
datos['Edad']

0     20
1     18
2     27
3     18
4     21
5     23
6     21
7     19
8     35
9     28
10    21
11    24
12    26
13    25
14    37
15    29
16    33
17    34
Name: Edad, dtype: int64

In [ ]:
datos['Nota']

0      7.5
1      NaN
2      2.5
3      5.0
4     10.0
5      NaN
6      7.0
7      6.0
8      5.6
9      NaN
10     NaN
11     4.5
12    10.0
13     9.0
14     NaN
15     7.0
16     NaN
17     8.0
Name: Nota, dtype: float64

In [ ]:
datos.dtypes

Nombre       object
Edad          int64
Nota        float64
Aprobado     object
dtype: object

## Calcula algunas estadísticas descriptivas básicas de los datos en el DataFrame (media, desviación estándar, etc.)

In [ ]:
datos.describe()

            Edad       Nota
count  18.000000  12.000000
mean   25.500000   6.841667
std     6.070662   2.264532
min    18.000000   2.500000
25%    21.000000   5.450000
50%    24.500000   7.000000
75%    28.750000   8.250000
max    37.000000  10.000000